# Main Configuration
main:
  containerCheckInterval: "5m"
  containerCheckOnChanges: true
  updateCheckInterval: ""
  prefix: ""

# MQTT Configuration
mqtt:
  connectionUri: "mqtt://127.0.0.1:1883"
  topic: "mqdockerup"
  discoveryPrefix: "homeassistant"
  suggestedArea: "Docker"
  clientId: "mqdockerup"
  username: "ha"
  password: ""
  haLegacy: false
  connectTimeout: 60
  protocolVersion: 5
  maxReconnectDelay: 300

# Access Tokens Configuration
accessTokens:
  dockerhub: ""
  github: ""

# Ignore Configuration
ignore:
  containers: ""
  updates: ""

# Logging Configuration
logs:
  level: "info"
